---
title: "Codebook"
author: "Alexandra Nechita"
date: "September 27, 2015"
output: html_document
---
Variable list and descriptions for the tify data set created

Variable name	Description
subject	ID the subject who performed the activity for each window sample. Its range is from 1 to 30.
Activity name 
featureName All the feature names that contain eiter mean or std functions
count Count of data points used to compute average
Average Average of each variable for each activity and each subject

Dataset Structure
str(dtTidy)
Classes ‘data.table’ and 'data.frame':	11880 obs. of  5 variables:
 $ subject     : int  1 1 1 1 1 1 1 1 1 1 ...
 $ activityName: Factor w/ 6 levels "LAYING","SITTING",..: 1 1 1 1 1 1 1 1 1 1 ...
 $ featureName : Factor w/ 477 levels "angle(tBodyAccJerkMean),gravityMean)",..: 43 44 45 56 57 58 94 95 96 107 ...
 $ count       : int  50 50 50 50 50 50 50 50 50 50 ...
 $ average     : num  -0.939 -0.867 -0.883 -0.924 -0.834 ...
 - attr(*, "sorted")= chr  "subject" "activityName" "featureName"
 - attr(*, ".internal.selfref")=<externalptr> 
 
List the key variables in the data table

key(dtTidy)
[1] "subject"      "activityName" "featureName" 

Show a few rows of the dataset

head(dtTidy)
subject activityName       featureName count    average
1:       1       LAYING fBodyAcc-mean()-X    50 -0.9390991
2:       1       LAYING fBodyAcc-mean()-Y    50 -0.8670652
3:       1       LAYING fBodyAcc-mean()-Z    50 -0.8826669
4:       1       LAYING  fBodyAcc-std()-X    50 -0.9244374
5:       1       LAYING  fBodyAcc-std()-Y    50 -0.8336256
6:       1       LAYING  fBodyAcc-std()-Z    50 -0.8128916

Summary of variables

summary(dtTidy)

subject                 activityName             featureName   
 Min.   : 1.0   LAYING            :1980   fBodyAcc-mean()-X:  180  
 1st Qu.: 8.0   SITTING           :1980   fBodyAcc-mean()-Y:  180  
 Median :15.5   STANDING          :1980   fBodyAcc-mean()-Z:  180  
 Mean   :15.5   WALKING           :1980   fBodyAcc-std()-X :  180  
 3rd Qu.:23.0   WALKING_DOWNSTAIRS:1980   fBodyAcc-std()-Y :  180  
 Max.   :30.0   WALKING_UPSTAIRS  :1980   fBodyAcc-std()-Z :  180  
                                          (Other)          :10800  
     count          average        
 Min.   :36.00   Min.   :-0.99767  
 1st Qu.:49.00   1st Qu.:-0.96205  
 Median :54.50   Median :-0.46989  
 Mean   :57.22   Mean   :-0.48436  
 3rd Qu.:63.25   3rd Qu.:-0.07836  
 Max.   :95.00   Max.   : 0.97451 
 
Save to file

Save data table objects to a tab-delimited text file called DatasetHumanActivityRecognitionUsingSmartphones.txt.

f <- file.path(path, "TidyDataSet.txt")
write.table(dtTidy, f, quote = FALSE, sep = "\t", row.names = FALSE)



